huh_encore:
  js_entries:
    - name: contao-lightbox-gallery-bundle
      file: 'vendor/heimrichhannot/contao-lightbox-gallery-bundle/src/Resources/assets/js/contao-lightbox-gallery-bundle.js'
      requires_css: true
  unset_global_keys:
    js:
      - lightbox-gallery
      - huh_components_glightbox_gallery
    css:
      - huh_components_glightbox_gallery